### ISSUE TITLE
running.tem

### ISSUE THREAD

**Issue by musicsnap** [ljj7410/Simple-Swoole-Framework#1]
#PHP Warning:  unlink(/data/wwwroot/default/Simple-Swoole-Framework/apps/runtime/tmp/running.tmp): No such file or directory in /data/wwwroot/default/Simple-Swoole-Framework/libs/root.php on line 101

第一次php index.php start 出现 但是生成之后在目录下有这个文件的

**Comment by simoole** [comment]
哦！是的，第一次启动时该临时文件并没有生成，缺少了一个判断，谢谢你的反馈！

**Comment by simoole** [comment]
问题已处理！:)
