### ISSUE TITLE
框架好像只有db的连接池,没redis的连接池

### ISSUE THREAD

**Issue by 493689** [ljj7410/Simple-Swoole-Framework#3]
redis的连接池要怎么调用呢

**Comment by simoole** [comment]
getRedis函数就可以算作是连接池，因为是常驻内存的实例，pconnect已经足够了
`
/**
 * 实例化并获取redis连接
 * @return null|Redis
 */
function getRedis()
{
    static $instance = null;
    if($instance === null || !$instance->ping()){
        $instance = new \Redis();
        $instance->pconnect(C('REDIS.host'), C('REDIS.port'), 0);
        $instance->auth(C('REDIS.pass'));
    }
    return $instance;
}
`

**Comment by 493689** [comment]
使用pconnect是否会造成达到连接上限后,后来的用户就连不上了,我之前的某个项目因为并发数很高(当时没用swoole),华为云的redis集群(其中一个,不是最贵的)连接数最高8万,然后就有一堆连接timout的错误,如果使用pconnect的话,是否会存在连接不会释放,然后新的用户连不上的问题呢?如果是连接池的话,连接结束自动回收,感觉应该可以解决这个问题?

**Comment by simoole** [comment]
没错，我已经把pconnect换成connect，同时也可以配置协程版redis连接方式。
新的3.0版本已经提交了，欢迎提出宝贵意见

**Comment by 493689** [comment]
好的,谢谢
